### PR TITLE
init nmf notebook

### PR DESCRIPTION
**Pull request by capital-G**
Another notebook which builds a bridge between machine learning, stft and matrix operations.

The notebook has a size of 25 mb due to the embedded audio samples - well...

### CODE REVIEW

**Comment by telephon** [comment]
Interesting to see this. Some of it I don't get just from reading, maybe because my terminology is different, which is OK. It looks like a phase vocoder? If we want to make the connection to the supercollider world, you could have a look at `pvcalc` and the other phase vocoder (fft) UGens.

One thing I am still not quite sure: How does this connect to machine learning?

**Comment by capital-G** [comment]
> Interesting to see this. Some of it I don't get just from reading, maybe because my terminology is different, which is OK.

Can you tell which bits are difficult to understand, then I will enhnace them some more

> It looks like a phase vocoder?

As phase is one of the components of STFT: yes, but most of the time we are using abs to get a representation which accounts for phase and amplitude.
The part where we split phase and amplitude could be indeed considered as phase vocoder - one could even just do a reduction on phase component.

> If we want to make the connection to the supercollider world, you could have a look at `pvcalc` and the other phase vocoder (fft) UGens.

Cool stuff, did not know this that phase manipulation via a function was possible in SC

> One thing I am still not quite sure: How does this connect to machine learning?

NMF is often used when working with text as it reduces the size - the idea: i can compress the dictionary down to combinations of words that occur and can work on this vectors instead of a matrix with 10^7 dimensionality due to the massive dictionary of my corpora as almost all ML algorithms do not work on these high dimensions, see https://en.wikipedia.org/wiki/Curse_of_dimensionality and sparse vs dense vectors which is described at https://www.tensorflow.org/tutorials/text/word_embeddings?hl=en

It also introduces the idea of compression due to learning/approximation and reversing the compression.
The neural network equivalent of this is an AutoEncoder which is the counterpart of GANs (and I prefer AE as they are easier to train and with [VQAE](https://blog.usejournal.com/understanding-vector-quantized-variational-autoencoders-vq-vae-323d710a888a) they can get the same performance as GANs) - the AE uses the notion of [latent space](https://towardsdatascience.com/understanding-latent-space-in-machine-learning-de5a7c687d8d) which is closely related with our compression when using NMF.

**Comment by telephon** [comment]
> > It looks like a phase vocoder?
> 
> As phase is one of the components of STFT: yes, but most of the time we are using abs to get a representation which accounts for phase and amplitude.

I actually meant just a simple vocoder.

**Comment by telephon** [comment]
I see. Perhaps a little bit more on this compression idea may be good for a general understaning of where this is heading (apart from being interesting by itself).

**Comment by telephon** [comment]
> Cool stuff, did not know this that phase manipulation via a function was possible in SC

It is just general reltime FFT processing via signals. There are many UGens, but with `pvcalc` you can roll your own. It is far less efficient than the UGens of course.

**Comment by capital-G** [comment]
I implemented the requested changes and added a paragraph about NMF <-> ML
Maybe this can be merged til the start of next session so it is available to everyone on the main branch and on the website?

When merging squashing should be applied as I failed to make the results deterministic at the beginning.

**Review by telephon — APPROVED** [review]

**Pull request merged**
